### ISSUE TITLE
How is hugoreleaser related to goreleaser (if at all)?

### ISSUE THREAD

**Issue by trallnag** [bep/hugoreleaser#35]
I'm currently looking into Goreleaser and was trying to figure out if it supports custom messages in changelogs. Came across [this](https://github.com/goreleaser/goreleaser/issues/183) several year old issue from you requesting a related feature. Now I wanted to see how things are setup in Hugo nowadays and discovered Hugoreleaser.

Now I am wondering if and how Hugoreleaser is related to the former?

**Comment by bep** [comment]
>Now I am wondering if and how Hugoreleaser is related to the former?

There are some lines in the README:

* https://github.com/gohugoio/hugoreleaser#why-another-go-release-tool

Hugo used to use `goreleaser` and it worked great. But there were some missing features, mainly being able to split the build step  into multiple Docker containers (that now is somewhat available in the Pro version of Goreleaser). This repo is implemented from scratch by me, and you may argue that that is putting a little too much work into something used by so few, but I learned a lot doing this. For one, the plugin system is something that I'm pretty happy with and consider pulling into Hugo somehow.

Some more info here:

https://github.com/gohugoio/hugo/releases/tag/v0.102.0

**Comment by trallnag** [comment]
Thanks for the insight, feel free to close the issue
